// client/src/views/EmailConfirmation/index.tsx
import React, { useEffect, useState } from 'react';
import { Link } from 'react-router';
import api from '../../api-service/api';
import ApiConfig from '../../api-service/apiConfig';

type Status = 'loading' | 'success' | 'error';

const EmailConfirmation: React.FC = () => {
  const [status, setStatus] = useState<Status>('loading');
  const [errorMessage, setErrorMessage] = useState<string>('');

  const confirmEmail = async (): Promise<void> => {
    const urlParams = new URLSearchParams(window.location.search);
    const id = urlParams.get('identification');
    if (!id) {
      setStatus('error');
      setErrorMessage('Wrong or missing identification.');
      return;
    }

    const payload = { identification: id };
    try {
      await api.postJSON(ApiConfig.confirmUrl, payload);
      setStatus('success');
    }
    catch (e) {
      setStatus('error');
      if (e instanceof Error) {
        setErrorMessage(e.message);
      }
      else {
        setErrorMessage(e as string);
      }
    }
  };

  useEffect(() => {
    confirmEmail();
  }, []);

  return (
    <div
      className="d-flex flex-column align-items-center justify-content-center min-vh-100 px-3 text-center"
      style={{
        backgroundColor: '#E6F5E9',
        color: '#212529',
        fontFamily: 'Poppins, sans-serif'
      }}
    >
      <link
        href="https://fonts.googleapis.com/css2?family=Poppins&display=swap"
        rel="stylesheet"
      />

      <div className="p-4 bg-white rounded-3 shadow" style={{ maxWidth: '500px', width: '100%' }}>

        {status === 'loading' && (
          <>
            <div className="spinner-border text-success mb-3"></div>
            <p>Confirming your email address...</p>
          </>
        )}

        {status === 'success' && (
          <>
            <h1 className="mb-3">✅ Email Confirmed</h1>

            <p className="mb-4">
              Thank you! Your email address has been successfully confirmed.
              You can now return to the TaskNote app and log in.
            </p>
            <Link to="/login" className="btn btn-success px-4 py-2"style={{ fontWeight: 'bold', borderRadius: '6px' }}>
              Go to Login
            </Link>
          </>
        )}

        {status === 'error' && (
          <>
            <h1 className="mb-3">❌ Oops!</h1>
            <p className="mb-4">
              { errorMessage }
            </p>
          </>
        )}

      </div>
    </div>
  );
};

export default EmailConfirmation;

// angular/src/app/components/email-confirmation/email-confirmation.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { CommonModule } from '@angular/common';
import { ApiService } from '../../services/api.service';

@Component({
  selector: 'app-email-confirmation',
  standalone: true,
  imports: [CommonModule, RouterLink],
  templateUrl: './email-confirmation.component.html'
})
export class EmailConfirmationComponent implements OnInit {
  status: string | null = 'loading';
  errorMessage: string | null = null;
  identification: string | null = null;

  constructor(private apiService: ApiService, private route: ActivatedRoute) {}

  ngOnInit(): void {
    // Get a single query parameter
    this.route.queryParamMap.subscribe(params => {
      this.identification = params.get('identification');
      console.log('Identification:', this.identification);
      
      // Now you can use the token to confirm the email
      if (this.identification) {
        this.confirmEmail();
      } else {
        this.status = 'error';
        this.errorMessage = 'Wrong or missing identification token.';
      }
    });
  }

  private confirmEmail(): void {
    this.apiService.confirmEmail(this.identification!).subscribe({
      next: () => {
        this.status = 'success';
      },
      error: (error) => {
        this.status = 'error';
        this.errorMessage = error.message || 'Failed to confirm email';
      }
    });
  }
}

<div *ngIf="status === 'loading'">
  <p>Confirming your email address...</p>
</div>

<div *ngIf="status === 'error'">
  <p>{{ errorMessage }}</p>
</div>

<div *ngIf="status === 'success'">
  <h1>Email Confirmed</h1>
  <p>
    Thank you! Your email address has been successfully confirmed.
    You can now return to the TaskNote app and log in.
  </p>
  <a routerLink="/">Go to Login</a>
</div>
